server:
  port: 8091

spring:
    aop:
      auto: true
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/tk_mysql01?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
                    # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
 
lcn:
  manager:
    server: 172.18.58.57
    port: 9090
